"""
13_crosscheck_export.py - independent check of the raw file against SingStat's own export.

raw/cpi_2024base_monthly.csv        downloaded from data.gov.sg on 7 September 2026
raw/cpi_2024base_monthly_tablebuilder.csv  exported from SingStat TableBuilder on
                                    8 September 2026, same table TS/M213751

Two different delivery paths for the same table. If every index value agrees, the
data.gov.sg copy is a faithful reproduction of SingStat's own numbers and the cleaning
in 01_clean.py reads them correctly. If they disagree, one of them is wrong and no
published figure can stand.
"""
import csv, hashlib, pathlib
import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
A = HERE / "raw" / "cpi_2024base_monthly.csv"
B = HERE / "raw" / "cpi_2024base_monthly_tablebuilder.csv"

print("md5 of each file (they are different exports, so these WILL differ):")
for f in (A, B):
    print(f"  {hashlib.md5(f.read_bytes()).hexdigest()}  {f.name}")

rows = list(csv.reader(B.open()))
meta = {r[0].split(":")[0].strip(): r[0].split(":", 1)[1].strip()
        for r in rows[:10] if r and ":" in r[0]}
print("\nTableBuilder export header:")
for k, v in meta.items():
    print(f"  {k}: {v}")

hdr_i = next(i for i, r in enumerate(rows) if r and r[0].strip() == "Data Series")
hdr = [c.strip() for c in rows[hdr_i]]
body = [r for r in rows[hdr_i+1:] if r and r[0].strip() and not r[0].startswith(
        ("Generated by", "Date generated", "Contact", "Footnote", "**"))]
print(f"\nTableBuilder: {len(body)} data rows, {len(hdr)-1} period columns")

def norm(p):
    p = p.strip()
    return f"{p[:4]}-{ {'Jan':1,'Feb':2,'Mar':3,'Apr':4,'May':5,'Jun':6,'Jul':7,'Aug':8,'Sep':9,'Oct':10,'Nov':11,'Dec':12}[p[5:8]]:02d}"

tb = {}
for r in body:
    name = r[0].strip()
    for j, col in enumerate(hdr[1:], start=1):
        if j >= len(r): break
        v = r[j].strip()
        if v in ("", "na", "-", "n.a."): continue
        tb[(name, norm(col))] = v

mine = pd.read_csv(HERE / "out" / "analysis.csv", dtype={"index": str})
dg = {(r.series, r.date): r._asdict()["index"] for r in mine.itertuples()}

print(f"\ndata.gov.sg via 01_clean.py: {len(dg)} observations")
print(f"TableBuilder export:         {len(tb)} observations")

common = set(tb) & set(dg)
only_tb = set(tb) - set(dg)
only_dg = set(dg) - set(tb)
print(f"\nin both: {len(common)}   only in TableBuilder: {len(only_tb)}   only in data.gov.sg: {len(only_dg)}")

mismatch = [(k, tb[k], dg[k]) for k in sorted(common) if tb[k] != dg[k]]
print(f"\nVALUE MISMATCHES among the {len(common)} shared observations: {len(mismatch)}")
for k, a, b in mismatch[:10]:
    print(f"   {k}: TableBuilder {a} vs data.gov.sg {b}")

print("\nSpot check of the numbers the article actually uses:")
for k in [("Water Supply","2022-12"),("Water Supply","2023-01"),
          ("Water Supply","2023-12"),("Water Supply","2024-01"),
          ("All Items","2023-01"),("All Items","2022-12"),
          ("Polytechnic Education","2022-12"),("Polytechnic Education","2023-01")]:
    a, b = tb.get(k), dg.get(k)
    flag = "MATCH" if a == b and a is not None else "CHECK"
    print(f"   {k[0]:24s} {k[1]}  TableBuilder {str(a):>9s}  data.gov.sg {str(b):>9s}  {flag}")

ok = (len(mismatch) == 0 and len(only_dg) == 0)
print("\n" + "="*74)
print("VERDICT:", "PASS. The two independent exports agree on every shared value."
      if ok else "FAIL. Investigate before publishing anything.")
print("="*74)
